name: appointment
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter_18pt-Black.ttf
          weight: 800
        - asset: fonts/Inter_18pt-Bold.ttf
          weight: 700
        - asset: fonts/Inter_18pt-Regular.ttf
          weight: 400
        - asset: fonts/Inter_18pt-ExtraBold.ttf
        - asset: fonts/Inter_18pt-Medium.ttf
          weight: 500
        - asset: fonts/Inter_18pt-Light.ttf
          weight: 300
        - asset: fonts/Inter_18pt-SemiBold.ttf
          weight: 600

  assets:
    - assets/images/
    - assets/images/auth/
